# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SnykTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
jobs:
  build:
    name: scanbuild
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml 
      
    - name: runsnykscan
      run: |
        echo run snyk scan using CLI...
        echo "Node Version: $(node --version)"
        echo "NPM version: $(npm --version)"
        brew tap snyk/tap
        brew install snyk
        snyk auth SNYK_TOKEN
        snyk test --all-projects
