name: snyk-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Snyksecurity:
    runs-on: ubuntu-latest
    steps:
    - uses: simple-java-maven-app/checkout@master
    - name: Run Snyk to check for vulnerabilities
    - uses: Joe-Imman/simple-java-maven-app/.github/workflows/snyktest@master
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: snyk-testing
      run: snyk test --json-file-output=snyk.json
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - uses: garethr/snyk-to-sarif@master
    - uses: actions/uplaod-artifact@v2
      with:
        name: SARIF
        path: snyk.sarif
    - name: Upload result to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif


